language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install
before_script:
- git config --global user.name 'EvilEpicCoder'
- git config --global user.email '1st.elixile@gmail.com'
# - sed -i'' "s~git@github.com:evilepiccoder/HexoHelloWorld.git~https://${4c15e2946f20f1f64426e449c1090f89827e8b1a}:x-oauth-basic@github.com/evilepiccoder/HexoHelloWorld/.git~" _config.yml

- sed -i "s/65568c272c057a31f50dc4c57e95ea383ce94c4f/${65568c272c057a31f50dc4c57e95ea383ce94c4f}/" _config.yml
install:
- npm run generate
script:
# - npm run build
- npm run deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "65568c272c057a31f50dc4c57e95ea383ce94c4f"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
