language: node_js
node_js:
  - "5"
branches:
  only:
  - master
before_install:
- npm install
before_script:
- git config --global user.name 'EvilEpicCoder'
- git config --global user.email '1st.elixile@gmail.com'
- sed -i'' "s~git@github.com:evilepiccoder/HexoHelloWorld.git~https://${GH_TOKEN}:x-oauth-basic@github.com/evilepiccoder/HexoHelloWorld/.git~" _config.yml
install:
- npm run generate
script:
- npm run deploy
env:
  global:
    secure: fsYO96363oEzxaG31uAO7Col7KBxZJTTK/KnVeQpF80
